"""App Process 模块 — 编排协调."""

from ditto_app.process.materialization import (
    CASCADE_MAX_RETRY_COUNT,
    REALTIME_CASCADE_MAX_DEPTH,
    CascadeDepthExceededError,
    CascadeStatus,
    DerivedInputProvider,
    DerivedMaterializationOrchestrator,
    DerivedPublicationFacade,
    FactorOrthogonalizationService,
    InMemoryDerivedInputProvider,
    InputContext,
    InvalidationCascadeOrchestrator,
    MissingDependencyError,
    RepairBatchResult,
    RuntimeDerivedInputProvider,
    UnavailableDerivedInputProvider,
    UniverseProvider,
    apply_cs_amplification,
    build_certification_checks,
    build_manifest_record,
    build_minimal_dq_record,
    dependency_refs,
    earliest_pending_start,
    hydrate_spec,
    resolve_shadow_baseline,
)
from ditto_app.process.strategy import (
    BacktestService,
    BacktestServiceConfig,
    BacktestServiceOptions,
    MarketServiceDataFeed,
    MarketServiceDataFeedConfig,
    RunLifecycleService,
    StrategyFacade,
    StrategyInputAssembler,
    StrategyRunMode,
    StrategyRunResult,
    StrategyRunService,
    StrategyRunServiceConfig,
    enrich_record_with_symbol,
    write_backtest_artifacts,
)

__all__ = [
    # -- materialization --
    "CASCADE_MAX_RETRY_COUNT",
    "REALTIME_CASCADE_MAX_DEPTH",
    # -- strategy --
    "BacktestService",
    "BacktestServiceConfig",
    "BacktestServiceOptions",
    "CascadeDepthExceededError",
    "CascadeStatus",
    "DerivedInputProvider",
    "DerivedMaterializationOrchestrator",
    "DerivedPublicationFacade",
    "FactorOrthogonalizationService",
    "InMemoryDerivedInputProvider",
    "InputContext",
    "InvalidationCascadeOrchestrator",
    "MarketServiceDataFeed",
    "MarketServiceDataFeedConfig",
    "MissingDependencyError",
    "RepairBatchResult",
    "RunLifecycleService",
    "RuntimeDerivedInputProvider",
    "StrategyFacade",
    "StrategyInputAssembler",
    "StrategyRunMode",
    "StrategyRunResult",
    "StrategyRunService",
    "StrategyRunServiceConfig",
    "UnavailableDerivedInputProvider",
    "UniverseProvider",
    "apply_cs_amplification",
    "build_certification_checks",
    "build_manifest_record",
    "build_minimal_dq_record",
    "dependency_refs",
    "earliest_pending_start",
    "enrich_record_with_symbol",
    "hydrate_spec",
    "resolve_shadow_baseline",
    "write_backtest_artifacts",
]
