"""DataHub models for data transfer objects."""

# DataHub 层自己的 models
from ditto_analytics.models.factors import (
    FACTOR_CLASS_FUNDAMENTAL,
    FACTOR_CLASS_MACRO,
    FACTOR_CLASS_STATISTICAL,
    FACTOR_CLASS_TECHNICAL,
    FACTOR_FAMILY_MOMENTUM,
    FACTOR_FAMILY_QUALITY,
    FACTOR_FAMILY_SIZE,
    FACTOR_FAMILY_VALUE,
    FACTOR_FAMILY_VOLATILITY,
    FactorClass,
    FactorFamily,
    FactorMetadata,
)
from ditto_analytics.models.features import (
    INDICATOR_TYPE_MOMENTUM,
    INDICATOR_TYPE_TREND,
    INDICATOR_TYPE_VOLATILITY,
    INDICATOR_TYPE_VOLUME,
    IndicatorMetadata,
    IndicatorType,
)
from ditto_kernel.enums import AssetClass, Exchange, OrderSide, RunStatus

from ditto_datahub.models.common import (
    AssetClassType,
    Dataset,
    DateScheduleType,
    Domain,
    InstrumentIdRange,
    OnDuplicate,
    Source,
)
from ditto_datahub.models.derived import (
    CompiledExpressionCacheRecord,
    CompiledExpressionOperatorRecord,
    DerivedCheckpointRecord,
    DerivedDependencyRecord,
    DerivedInvalidationRecord,
    DerivedPartitionRecord,
    DerivedRunRecord,
    DerivedSpecRecord,
    DerivedStateRecord,
    DerivedVersionRecord,
)
from ditto_datahub.models.ingestion import (
    DataChangedError,
    DataLateArrivalPolicy,
    IngestionCursor,
    IngestionLog,
    IngestionStatus,
    LateArrivalCheckResult,
    LateArrivalRejectedError,
    NotTradingDayError,
)
from ditto_datahub.models.macro import MacroCategory, MacroFrequency
from ditto_datahub.models.market import (
    BAR_ENRICHED_SCHEMA,
    BAR_SCHEMA,
    QUOTE_SCHEMA,
)
from ditto_datahub.models.metadata import (
    CalendarDay,
    ETFExtension,
    IndexExtension,
    IndustryBasic,
    IndustryMapping,
    InstrumentExtension,
    InstrumentRegistration,
    StockExtension,
)
from ditto_datahub.models.publication_safety import (
    CertificationReportRecord,
    CompatibilityManifestRecord,
    DerivedMinimalDQSummaryRecord,
    DerivedShadowSlotRecord,
    ShadowDiffReportRecord,
    ShadowTraceRecordRecord,
)
from ditto_datahub.models.source_codes import (
    COMMODITY_CODE_TO_INSTRUMENT_ID,
    FX_CODE_TO_INSTRUMENT_ID,
    METAL_CODE_ALIASES,
    VIX_CODE_TO_INSTRUMENT_ID,
)
from ditto_datahub.models.storage import FreezeManifest, WriteResult, WriteStoreResult
from ditto_datahub.models.strategy import (
    ArtifactKind,
    MarketState,
    Signal,
    SignalType,
    StrategyArtifactRecord,
    StrategySpecRecord,
)
from ditto_datahub.models.strategy_audit import (
    AuditRecordType,
    PreTradeDecisionPayload,
    RiskScanPayload,
)
from ditto_datahub.models.strategy_run import StrategyRunRecord

__all__ = [
    "BAR_ENRICHED_SCHEMA",
    "BAR_SCHEMA",
    "COMMODITY_CODE_TO_INSTRUMENT_ID",
    "FACTOR_CLASS_FUNDAMENTAL",
    "FACTOR_CLASS_MACRO",
    "FACTOR_CLASS_STATISTICAL",
    "FACTOR_CLASS_TECHNICAL",
    "FACTOR_FAMILY_MOMENTUM",
    "FACTOR_FAMILY_QUALITY",
    "FACTOR_FAMILY_SIZE",
    "FACTOR_FAMILY_VALUE",
    "FACTOR_FAMILY_VOLATILITY",
    "FX_CODE_TO_INSTRUMENT_ID",
    "INDICATOR_TYPE_MOMENTUM",
    "INDICATOR_TYPE_TREND",
    "INDICATOR_TYPE_VOLATILITY",
    "INDICATOR_TYPE_VOLUME",
    "METAL_CODE_ALIASES",
    "QUOTE_SCHEMA",
    "VIX_CODE_TO_INSTRUMENT_ID",
    "ArtifactKind",
    "AssetClass",
    "AssetClassType",
    "AuditRecordType",
    "CalendarDay",
    "CertificationReportRecord",
    "CompatibilityManifestRecord",
    "CompiledExpressionCacheRecord",
    "CompiledExpressionOperatorRecord",
    "DataChangedError",
    "DataLateArrivalPolicy",
    "Dataset",
    "DateScheduleType",
    "DerivedCheckpointRecord",
    "DerivedDependencyRecord",
    "DerivedInvalidationRecord",
    "DerivedMinimalDQSummaryRecord",
    "DerivedPartitionRecord",
    "DerivedRunRecord",
    "DerivedShadowSlotRecord",
    "DerivedSpecRecord",
    "DerivedStateRecord",
    "DerivedVersionRecord",
    "Domain",
    "ETFExtension",
    "Exchange",
    "FactorClass",
    "FactorFamily",
    "FactorMetadata",
    "FreezeManifest",
    "IndexExtension",
    "IndicatorMetadata",
    "IndicatorType",
    "IndustryBasic",
    "IndustryMapping",
    "IngestionCursor",
    "IngestionLog",
    "IngestionStatus",
    "InstrumentExtension",
    "InstrumentIdRange",
    "InstrumentRegistration",
    "LateArrivalCheckResult",
    "LateArrivalRejectedError",
    "MacroCategory",
    "MacroFrequency",
    "MarketState",
    "NotTradingDayError",
    "OnDuplicate",
    "OrderSide",
    "PreTradeDecisionPayload",
    "RiskScanPayload",
    "RunStatus",
    "ShadowDiffReportRecord",
    "ShadowTraceRecordRecord",
    "Signal",
    "SignalType",
    "Source",
    "StockExtension",
    "StrategyArtifactRecord",
    "StrategyRunRecord",
    "StrategySpecRecord",
    "WriteResult",
    "WriteStoreResult",
]
