"""SourceSchema definitions for different domains."""

from ditto_datahub.sources.schemas.capital_schemas import (
    BALANCE_SHEET_SOURCE_SCHEMA,
    CASH_FLOW_SOURCE_SCHEMA,
    CORPORATE_ACTIONS_SOURCE_SCHEMA,
    DIVIDEND_SOURCE_SCHEMA,
    FUTURES_SOURCE_SCHEMA,
    INCOME_STATEMENT_SOURCE_SCHEMA,
    INDEX_COMPOSITION_SOURCE_SCHEMA,
    MARGIN_TRADING_SOURCE_SCHEMA,
    PLEDGE_RATIO_SOURCE_SCHEMA,
    VALUATION_METRICS_SOURCE_SCHEMA,
)
from ditto_datahub.sources.schemas.metadata_schemas import (
    INDEX_MEMBER_SOURCE_SCHEMA,
    INDUSTRY_SOURCE_SCHEMA,
    INSTRUMENT_SOURCE_SCHEMA,
)

__all__ = [
    "BALANCE_SHEET_SOURCE_SCHEMA",
    "CASH_FLOW_SOURCE_SCHEMA",
    "CORPORATE_ACTIONS_SOURCE_SCHEMA",
    "DIVIDEND_SOURCE_SCHEMA",
    "FUTURES_SOURCE_SCHEMA",
    "INCOME_STATEMENT_SOURCE_SCHEMA",
    "INDEX_COMPOSITION_SOURCE_SCHEMA",
    "INDEX_MEMBER_SOURCE_SCHEMA",
    "INDUSTRY_SOURCE_SCHEMA",
    "INSTRUMENT_SOURCE_SCHEMA",
    "MARGIN_TRADING_SOURCE_SCHEMA",
    "PLEDGE_RATIO_SOURCE_SCHEMA",
    "VALUATION_METRICS_SOURCE_SCHEMA",
]
