"""Models 包。"""

from __future__ import annotations

from ditto_interfaces.models.backtest import (
    AuditRecordResponse,
    BenchmarkNavResponse,
    RunResponse,
    RunsQueryParams,
    TradeResponse,
    to_audit_record_response,
    to_run_response,
)
from ditto_interfaces.models.capital import (
    Margin,
    MarginQuery,
    Valuation,
    ValuationQuery,
    to_margin,
    to_margin_list,
    to_valuation,
    to_valuation_list,
)
from ditto_interfaces.models.commodity import (
    CommodityBar,
    CommodityQuery,
    to_commodity_bar,
    to_commodity_bar_list,
)
from ditto_interfaces.models.common import (
    APIResponse,
    ErrorResponse,
    PaginationRequest,
    PaginationResponse,
)
from ditto_interfaces.models.fundamental import (
    CorporateAction,
    CorporateActionsQuery,
    Dividend,
    DividendQuery,
    Financial,
    FinancialQuery,
    FinancialType,
    to_corporate_action,
    to_corporate_action_list,
    to_dividend,
    to_dividend_list,
    to_financial,
    to_financial_list,
)
from ditto_interfaces.models.fx import (
    FxBar,
    FxQuery,
    to_fx_bar,
    to_fx_bar_list,
)
from ditto_interfaces.models.macro import (
    Indicator,
    IndicatorQuery,
    to_indicator,
    to_indicator_list,
)
from ditto_interfaces.models.market import (
    Adjustment,
    Bar,
    BarsQuery,
    to_bar,
    to_bar_list,
)
from ditto_interfaces.models.metadata import (
    Instrument,
    InstrumentQuery,
    to_instrument,
    to_instrument_list,
)
from ditto_interfaces.models.strategy import (
    CreateStrategyRequest,
    PublishStrategyRequest,
    StrategyResponse,
    UpdateStrategyRequest,
    to_strategy_response,
)
from ditto_interfaces.models.trade import (
    ComparisonMetricsResponse,
    FillResponse,
    PnlSummaryResponse,
    PositionSnapshotResponse,
    RecordFillRequest,
    TradeIntentResponse,
    UpdateIntentStatusRequest,
)

__all__ = [
    "APIResponse",
    "Adjustment",
    "AuditRecordResponse",
    "Bar",
    "BarsQuery",
    "BenchmarkNavResponse",
    "CommodityBar",
    "CommodityQuery",
    "ComparisonMetricsResponse",
    "CorporateAction",
    "CorporateActionsQuery",
    "CreateStrategyRequest",
    "Dividend",
    "DividendQuery",
    "ErrorResponse",
    "FillResponse",
    "Financial",
    "FinancialQuery",
    "FinancialType",
    "FxBar",
    "FxQuery",
    "Indicator",
    "IndicatorQuery",
    "Instrument",
    "InstrumentQuery",
    "Margin",
    "MarginQuery",
    "PaginationRequest",
    "PaginationResponse",
    "PnlSummaryResponse",
    "PositionSnapshotResponse",
    "PublishStrategyRequest",
    "RecordFillRequest",
    "RunResponse",
    "RunsQueryParams",
    "StrategyResponse",
    "TradeIntentResponse",
    "TradeResponse",
    "UpdateIntentStatusRequest",
    "UpdateStrategyRequest",
    "Valuation",
    "ValuationQuery",
    "to_audit_record_response",
    "to_bar",
    "to_bar_list",
    "to_commodity_bar",
    "to_commodity_bar_list",
    "to_corporate_action",
    "to_corporate_action_list",
    "to_dividend",
    "to_dividend_list",
    "to_financial",
    "to_financial_list",
    "to_fx_bar",
    "to_fx_bar_list",
    "to_indicator",
    "to_indicator_list",
    "to_instrument",
    "to_instrument_list",
    "to_margin",
    "to_margin_list",
    "to_run_response",
    "to_strategy_response",
    "to_valuation",
    "to_valuation_list",
]
