"""Compatibility exports for the shared StrategySpec deserialization boundary."""

from ditto_application.strategy_spec_deserialization import (
    _DEFAULT_MAX_WEIGHT,
    _DEFAULT_SLIPPAGE_BPS,
    _DEFAULT_TOP_K,
    _DEFAULT_TRAILING_STOP_PCT,
    _normalize_impact_model,
    default_required_datasets_for_template,
    deserialize_constraint,
    deserialize_constraints,
    deserialize_cost_model,
    deserialize_execution,
    deserialize_param_constraint,
    deserialize_param_constraints,
    deserialize_scorer,
    deserialize_selector,
    deserialize_strategy_spec,
    deserialize_strategy_spec_v2,
    inject_template_constraints,
)

__all__ = [
    "_DEFAULT_MAX_WEIGHT",
    "_DEFAULT_SLIPPAGE_BPS",
    "_DEFAULT_TOP_K",
    "_DEFAULT_TRAILING_STOP_PCT",
    "_normalize_impact_model",
    "default_required_datasets_for_template",
    "deserialize_constraint",
    "deserialize_constraints",
    "deserialize_cost_model",
    "deserialize_execution",
    "deserialize_param_constraint",
    "deserialize_param_constraints",
    "deserialize_scorer",
    "deserialize_selector",
    "deserialize_strategy_spec",
    "deserialize_strategy_spec_v2",
    "inject_template_constraints",
]
