"""
Ditto 共享模块.

提供跨项目的共享类型、配置和工具。
"""

from ditto_platform.foundation.cache import CacheStats, DataCache
from ditto_platform.foundation.checksum import compute_checksum
from ditto_platform.foundation.concurrency import FileLockManager, LockAcquisitionError
from ditto_platform.foundation.config import (
    ConfigInitCoordinator,
    ConfigInitError,
    ConfigInitProvider,
    ConfigLoader,
    Environment,
    InitResult,
    InitScope,
    ObservabilitySettings,
    PathResolver,
    Settings,
    SystemSettings,
    XDGPaths,
    find_project_root,
    get_environment,
)
from ditto_platform.foundation.config.providers import (
    ConfigValidationProvider,
    DataRootInitProvider,
)
from ditto_platform.foundation.db import SQLitePool
from ditto_platform.foundation.json_types import (
    JsonDict,
    JsonPrimitive,
    JsonValue,
    require_bool,
    require_int,
    require_payload,
    require_str,
)
from ditto_platform.foundation.observability import (
    EffectiveConfig,
    Metrics,
    ObservabilityConfig,
    SafeCounter,
    SafeGauge,
    SafeHistogram,
    get_recorded_metrics,
    get_recorded_spans,
    get_span_id,
    get_trace_id,
    init,
    logger,
    register_metric_definitions,
    reset_for_testing,
    shutdown,
    span,
    traced,
)
from ditto_platform.foundation.storage import (
    DatasetReader,
    DatasetWriter,
    MergeResult,
    OnDuplicate,
    ParquetStore,
    PartitionStrategy,
    SQLiteClient,
    SqliteReader,
    SqliteWriter,
    WriteResult,
    WriteStoreResult,
    YearlyPartition,
)
from ditto_platform.foundation.util import (
    ChecksumCompute,
    DateInput,
    atomic_bytes_write,
    atomic_write,
    file_md5,
    normalize_date,
)

__all__ = [
    "CacheStats",
    "ChecksumCompute",
    "ConfigInitCoordinator",
    "ConfigInitError",
    "ConfigInitProvider",
    "ConfigLoader",
    "ConfigValidationProvider",
    "DataCache",
    "DataRootInitProvider",
    "DatasetReader",
    "DatasetWriter",
    "DateInput",
    "EffectiveConfig",
    "Environment",
    "FileLockManager",
    "InitResult",
    "InitScope",
    "JsonDict",
    "JsonPrimitive",
    "JsonValue",
    "LockAcquisitionError",
    "MergeResult",
    "Metrics",
    "ObservabilityConfig",
    "ObservabilitySettings",
    "OnDuplicate",
    "ParquetStore",
    "PartitionStrategy",
    "PathResolver",
    "SQLiteClient",
    "SQLitePool",
    "SafeCounter",
    "SafeGauge",
    "SafeHistogram",
    "Settings",
    "SqliteReader",
    "SqliteWriter",
    "SystemSettings",
    "WriteResult",
    "WriteStoreResult",
    "XDGPaths",
    "YearlyPartition",
    "atomic_bytes_write",
    "atomic_write",
    "compute_checksum",
    "file_md5",
    "find_project_root",
    "get_environment",
    "get_recorded_metrics",
    "get_recorded_spans",
    "get_span_id",
    "get_trace_id",
    "init",
    "logger",
    "normalize_date",
    "register_metric_definitions",
    "require_bool",
    "require_int",
    "require_payload",
    "require_str",
    "reset_for_testing",
    "shutdown",
    "span",
    "traced",
]
